### PR TITLE
[MANIFEST] Added file mimetype exception of app/json for the Forms related services

### PR DESCRIPTION
**Pull request by jimleroyer**
## What happens when your PR merges?

The Forms team will be allowed to send attachments with mimetype `application/json`:

```sh
$ make diff-production
< EXTRA_MIME_TYPES=...
---
> EXTRA_MIME_TYPES=...
```

## Provide some background on the changes

The Forms team need to attach JSON files to their notifications.

## If you are releasing a new version of Notify, what components are you updating
- [ ] API
- [ ] Admin
- [ ] Documentation
- [ ] Document download API

## Checklist if releasing new version:
- [ ] I made sure that the changes are as expected in [Notify staging](https://staging.notification.cdssandbox.xyz/)
- [ ] I have checked if the docker images I am referencing exist
    - [ ] [api lambda](https://ca-central-1.console.aws.amazon.com/ecr/repositories/private/296255494825/notify/api-lambda?region=ca-central-1) (requires Notification-Production / AdministratorAccess login)
    - [ ] [api k8s](https://gallery.ecr.aws/v6b8u5o6/notify-api)
    - [ ] [admin](https://gallery.ecr.aws/v6b8u5o6/notify-admin)
    - [ ] [documentation](https://gallery.ecr.aws/v6b8u5o6/notify-documentation)
    - [ ] [document download API](https://gallery.ecr.aws/v6b8u5o6/notify-document-download-api)

## Checklist if making changes to Kubernetes:
- [ ] I know how to get kubectl credentials in case it catches on fire

## After merging this PR
- [ ] I have verified that the tests / deployment actions succeeded
- [ ] I have verified that any affected pods were restarted successfully
- [ ] I have verified that I can still log into [Notify production](https://notification.canada.ca)
- [ ] I have verified that the smoke tests still pass on production
- [ ] I have communicated the release in the #notify Slack channel.

### CODE REVIEW

**Review by andrewleith — APPROVED** [review]
Other than the conflict you have it looks good, I see the two new services and mime-types.

**Review by whabanks — APPROVED** [review]
Looking good to me, I see the mime-types and two new services. Are the Redis URL changes intentional?

**Comment by jimleroyer** [comment]
@whabanks There was a conflict that I solved, so these Redis URL changes shouldn't be there anymore.

**Review by sastels — APPROVED** [review]
checked locally

**Pull request merged**
