### PR TITLE
chore: cleanup and sync environment variables

### PR DESCRIPTION
**Pull request by patheard**
# Summary
The commit synchronizes the environment variable keys across
Staging, Production and the env.example file.  The changes are
as follows:

1. Remove `RECAPTCHA_PUBLIC_KEY` and `RECAPTCHA_PRIVATE_KEY`
which were part of an admin  pilot that is not going forward.
2. Remove a space from the end of Prod's `FF_REDIS_BATCH_SAVING`
value.
3. Set `MLWR_HOST` from the env var files, updating both Staging
and Production to have `MLWR_HOST=False`.
4. Add a blank `SENSITIVE_SERVICES` value to Staging.
5. Add `GC_ARTICLES_API_AUTH_USERNAME` and
`GC_ARTICLES_API_AUTH_PASSWORD` to Production.

# Related
* cds-snc/notification-planning#421
* cds-snc/notification-planning#424
* #952 

## What are you changing?
- [ ] Releasing a new version of Notify
- [x] Changing kubernetes configuration

## If you are releasing a new version of Notify, what components are you updating
- [ ] API
- [ ] Admin
- [ ] Documentation
- [ ] Document download API
- [ ] Document download frontend

## Checklist if releasing new version:
- [ ] I made sure that the changes are as expected in [Notify staging](https://staging.notification.cdssandbox.xyz/)
- [ ] I have checked if the docker images I am referencing exist
    - [ ] [api lambda](https://ca-central-1.console.aws.amazon.com/ecr/repositories/private/296255494825/notify/api-lambda?region=ca-central-1) (requires Notification-Production / AdministratorAccess login)
    - [ ] [api k8s](https://gallery.ecr.aws/v6b8u5o6/notify-api)
    - [ ] [admin](https://gallery.ecr.aws/v6b8u5o6/notify-admin)
    - [ ] [documentation](https://gallery.ecr.aws/v6b8u5o6/notify-documentation)
    - [ ] [document download API](https://gallery.ecr.aws/v6b8u5o6/notify-document-download-api)
    - [ ] [document download frontend](https://gallery.ecr.aws/v6b8u5o6/notify-document-download-frontend)

## Checklist if making changes to Kubernetes:
- [ ] I know how to get kubectl credentials in case it catches on fire

## After merging this PR
- [ ] I have verified that the tests / deployment actions succeeded
- [ ] I have verified that any affected pods were restarted successfully
- [ ] I have verified that I can still log into [Notify production](https://notification.canada.ca)
- [ ] I have verified that the smoke tests still pass on production
- [ ] I have communicated the release in the #notify Slack channel.

### CODE REVIEW

**Comment by patheard** [comment]
Changes to the env var files:

# Staging
```diff
make diff-staging

< MLWR_HOST=https://mlwr.ca
---
> MLWR_HOST=False
46a47
> SENSITIVE_SERVICES=
58,59d58
< RECAPTCHA_PUBLIC_KEY=<public-key-value>
< RECAPTCHA_PRIVATE_KEY=<private-key-value>
```

# Production
```diff
make diff-production                            

< FF_REDIS_BATCH_SAVING=false 
---
> FF_REDIS_BATCH_SAVING=false
49c49
< MLWR_HOST=https://mlwr.ca
---
> MLWR_HOST=False
78a79,81
> 
> GC_ARTICLES_API_AUTH_USERNAME=<api-username>
> GC_ARTICLES_API_AUTH_PASSWORD=<api-password>
```

**Review by sastels — APPROVED** [review]
LGTM. Would this be a good time to put the variables in the same order / spacing? Up to you.

**Comment by patheard** [comment]
> LGTM. Would this be a good time to put the variables in the same order / spacing? Up to you.

Not a bad idea at all.  I also wasn't planning to merge this before our prod release tomorrow so that I don't accidentally muddy any water.

**Comment by jimleroyer** [comment]
The staging value for GC articles were copied over to production?

**Review by jimleroyer — APPROVED** [review]
LGTM! :shipit:

**Comment by patheard** [comment]
> The staging value for GC articles were copied over to production?

Yup, that's correct, and since we aren't specifying a `GC_ARTICLES_API` env var, it will default to using the Staging GC Articles URL for API requests.

**Pull request merged**
