### PR TITLE
feat: remove document-download-frontend from cluster

### PR DESCRIPTION
**Pull request by sastels**
## What are you changing?
- [ ] Releasing a new version of Notify
- [x] Changing kubernetes configuration

## Provide some background on the changes

After https://github.com/cds-snc/notification-terraform/pull/502 is released to production we will no longer be using the document-download-frontend. We can then remove it from our cluster. That is done in this PR.

Note that apparently document-download-frontend was the only place the `ADMIN_CLIENT_USER_NAME` environment variable was used. So I deleted that as well.

```
AWS_PROFILE=notify-staging make diff-staging
< ADMIN_CLIENT_USER_NAME=...
```

```
AWS_PROFILE=notify-prod make diff-production
< ADMIN_CLIENT_USER_NAME=...
```

Note:
- ~first release that PR~ DONE
- ~then use the queries at the bottom of that PR to verify that requests to document.notification.canada.ca get routed to the document-download-api pod~ DONE

## If you are releasing a new version of Notify, what components are you updating
- [ ] API
- [ ] Admin
- [ ] Documentation
- [ ] Document download API
- [x] Document download frontend

## Checklist if releasing new version:
- [ ] I made sure that the changes are as expected in [Notify staging](https://staging.notification.cdssandbox.xyz/)
- [ ] I have checked if the docker images I am referencing exist
    - [ ] [api lambda](https://ca-central-1.console.aws.amazon.com/ecr/repositories/private/296255494825/notify/api-lambda?region=ca-central-1) (requires Notification-Production / AdministratorAccess login)
    - [ ] [api k8s](https://gallery.ecr.aws/v6b8u5o6/notify-api)
    - [ ] [admin](https://gallery.ecr.aws/v6b8u5o6/notify-admin)
    - [ ] [documentation](https://gallery.ecr.aws/v6b8u5o6/notify-documentation)
    - [ ] [document download API](https://gallery.ecr.aws/v6b8u5o6/notify-document-download-api)
    - [ ] [document download frontend](https://gallery.ecr.aws/v6b8u5o6/notify-document-download-frontend)

## Checklist if making changes to Kubernetes:
- [ ] I know how to get kubectl credentials in case it catches on fire

## After merging this PR
- [ ] I have verified that the tests / deployment actions succeeded
- [ ] I have verified that any affected pods were restarted successfully
- [ ] I have verified that I can still log into [Notify production](https://notification.canada.ca)
- [ ] I have verified that the smoke tests still pass on production
- [ ] I have communicated the release in the #notify Slack channel.

### CODE REVIEW

**Comment by jzbahrai** [comment]
Reviewed:
```
➜  notification-manifests git:(remove-document-download-frontend) make diff-production
Archive:  .previous.env.zip
  inflating: .env
Archive:  .env.zip
  inflating: .env
2d1
< ADMIN_CLIENT_USER_NAME=notify-admin
make: *** [diff-production] Error 1
```

```
➜  notification-manifests git:(remove-document-download-frontend) make diff-staging
Archive:  .previous.env.zip
  inflating: .env
Archive:  .env.zip
  inflating: .env
2d1
< ADMIN_CLIENT_USER_NAME=notify-admin
make: *** [diff-staging] Error 1
```

other than this it looks good to me

**Comment by sastels** [comment]
> Reviewed:
> 
> ```
> ➜  notification-manifests git:(remove-document-download-frontend) make diff-production
> Archive:  .previous.env.zip
>   inflating: .env
> Archive:  .env.zip
>   inflating: .env
> 2d1
> < ADMIN_CLIENT_USER_NAME=notify-admin
> make: *** [diff-production] Error 1
> ```
> 
> ```
> ➜  notification-manifests git:(remove-document-download-frontend) make diff-staging
> Archive:  .previous.env.zip
>   inflating: .env
> Archive:  .env.zip
>   inflating: .env
> 2d1
> < ADMIN_CLIENT_USER_NAME=notify-admin
> make: *** [diff-staging] Error 1
> ```
> 
> other than this it looks good to me

👍 I removed this env var on purpose - the only place it was used was the document-download-frontend

**Comment by sastels** [comment]
redid the env var files to fix merge conflict, still get
```
$ AWS_PROFILE=notify-staging make diff-staging
< ADMIN_CLIENT_USER_NAME=notify-admin

$ AWS_PROFILE=notify-prod make diff-production
< ADMIN_CLIENT_USER_NAME=notify-admin
```
as expected.

**Review by jzbahrai — APPROVED** [review]

**Comment by jzbahrai** [comment]
This PR has been open since august 16. can we move it to draft status or merge it?

**Comment by sastels** [comment]
To confirm that we removed the route to the document-download-frontend pod, I send myself a file link on prod, then verified that

https://document.notification.canada.ca/services/<service_id>/documents/<document_id>?key=<key>&filename=test_file.txt

will download the file. This is where the frontend pod used to live, but that endpoint is in document-download-api, not document-download-frontend, so the url now points to document-download-api.

**Pull request merged**
